//this code is generated by chat GPT !!!

import java.util.Scanner;

class Complex {
    private double real;
    private double imag;

    public Complex(double real, double imag) {
        this.real = real;
        this.imag = imag;
    }

    public Complex add(Complex other) {
        double realSum = this.real + other.real;
        double imagSum = this.imag + other.imag;
        return new Complex(realSum, imagSum);
    }

    public Complex subtract(Complex other) {
        double realDiff = this.real - other.real;
        double imagDiff = this.imag - other.imag;
        return new Complex(realDiff, imagDiff);
    }

    public Complex multiply(Complex other) {
        double realProd = this.real * other.real - this.imag * other.imag;
        double imagProd = this.real * other.imag + this.imag * other.real;
        return new Complex(realProd, imagProd);
    }

    public String toString() {
        if (imag >= 0) {
            return real + " + " + imag + "i";
        } else {
            return real + " - " + (-imag) + "i";
        }
    }
}

public class complx {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        System.out.println("Enter the real and imaginary parts of the first complex number:");
        double real1 = input.nextDouble();
        double imag1 = input.nextDouble();
        Complex num1 = new Complex(real1, imag1);

        System.out.println("Enter the real and imaginary parts of the second complex number:");
        double real2 = input.nextDouble();
        double imag2 = input.nextDouble();
        Complex num2 = new Complex(real2, imag2);

        Complex sum = num1.add(num2);
        Complex diff = num1.subtract(num2);
        Complex prod = num1.multiply(num2);

        System.out.println("Sum: " + sum);
        System.out.println("Difference: " + diff);
        System.out.println("Product: " + prod);
    }
}
